### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by xan2622** [s0undt3ch/wide-my-github#4]
Hello.

Could you add some screenshots in  README.md  ?
Just to let your users have a sneek peak.

Thanks

**Comment by s0undt3ch** [comment]
There's one screenshot [here](https://userstyles.org/styles/97661/wide-my-github) but I'm now using https://userstyles.org/styles/108591/github-wide and https://userstyles.org/styles/108592/github-gist-wide and won't be updating this style any more.
